### ISSUE TITLE
Doesn't work for AU Region

### ISSUE THREAD

**Issue by InyoEndo** [ad-ha/mg-saic-ha#29]
Tried to login with email/password for Australia region, doesnt work. Tried each of the regions. For reference, these are the required settings for the saic-python-mqtt-gateway if helps.

saic_rest_uri:
[https://gateway-mg-au.soimt.com/api.app/v1/ 5](https://gateway-mg-au.soimt.com/api.app/v1/)

saic_region:
au

**Comment by ad-ha** [comment]
Hi @InyoEndo 

Can you please check and try this: https://github.com/ad-ha/mg-saic-ha/issues/27#issuecomment-2476696279

There's a beta version addressing this that seems to be working.

Cheers

**Comment by InyoEndo** [comment]
@ad-ha yup seems to work. Should have checked close tickets first I guess :)

**Comment by ad-ha** [comment]
No worries.

Glad it's working. I should be releasing a stable version in the next couple of hours.

**Comment by InyoEndo** [comment]
Ugh spoke too soon.

Traceback (most recent call last):
  File "/config/custom_components/mg_saic/coordinator.py", line 73, in _async_update_data
    self._is_generic_charging_response(charging_info)
  File "/config/custom_components/mg_saic/coordinator.py", line 186, in _is_generic_charging_response
    raise GenericResponseException(
custom_components.mg_saic.coordinator.GenericResponseException: Generic charging response received.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/__init__.py", line 42, in async_setup_entry
    await coordinator.async_setup()
  File "/config/custom_components/mg_saic/coordinator.py", line 53, in async_setup
    await self.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 309, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/coordinator.py", line 136, in _async_update_data
    await asyncio.sleep(delay)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by ad-ha** [comment]
New release 0.4.7 done.

Check if this fixes the issues.

**Comment by InyoEndo** [comment]
All works looks good, will check it out in morning as have charging automations setup so need MQTT integration running overnight
