### ISSUE TITLE
[ISSUE] Has become unavailable

### ISSUE THREAD

**Issue by nestor1832** [ad-ha/mg-saic-ha#37]
### Home Assistant Version

2024.11.2

### MG/SAIC Integration Version

0.4.8

### Installation Method

HACS

### Did you check for existing issues?

- [X] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [X] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

After successfully receiving the data two hours ago, nothing was updated, although I requested an update of the data manually with the button: “Update Vehicle Data”.
I reloaded the application several times, more than 8 times ;-) and now all the data is unavailable.
![Capture d’écran du 2024-11-19 18-10-18](https://github.com/user-attachments/assets/91463fb3-eb38-4081-a2b7-4c0c03a60e57)

### Logs

```yaml
2024-11-19 17:53:00.231 DEBUG (MainThread) [custom_components.mg_saic] Generic Charging Data: ChrgMgmtData(bmsAdpPubChrgSttnDspCmd=0, bmsAltngChrgCrntDspCmd=0, bmsChrgCtrlDspCmd=0, bmsChrgOtptCrntReq=511, bmsChrgOtptCrntReqV=1, bmsChrgSpRsn=0, bmsChrgSts=0, bmsDsChrgSpRsn=0, bmsEstdElecRng=2046, bmsOnBdChrgTrgtSOCDspCmd=0, bmsPackCrnt=65535, bmsPackCrntV=1, bmsPackSOCDsp=1023, bmsPackVol=4095, bmsPTCHeatReqDspCmd=0, bmsPTCHeatResp=0, bmsPTCHeatSpRsn=None, bmsReserCtrlDspCmd=0, bmsReserSpHourDspCmd=30, bmsReserSpMintueDspCmd=62, bmsReserStHourDspCmd=30, bmsReserStMintueDspCmd=62, ccuEleccLckCtrlDspCmd=0, ccuOffBdChrgrPlugOn=0, ccuOnbdChrgrPlugOn=0, chrgngAddedElecRng=0, chrgngAddedElecRngV=0, chrgngDoorOpenCnd=0, chrgngDoorPosSts=0, chrgngRmnngTime=1023, chrgngRmnngTimeV=1, chrgngSpdngTime=0, chrgngSpdngTimeV=0, clstrElecRngToEPT=2046, disChrgngRmnngTime=1023, disChrgngRmnngTimeV=1, imcuChrgngEstdElecRng=2046, imcuChrgngEstdElecRngV=1, imcuDschrgngEstdElecRng=4095, imcuDschrgngEstdElecRngV=1, imcuVehElecRng=2046, imcuVehElecRngV=1, onBdChrgrAltrCrntInptCrnt=0, onBdChrgrAltrCrntInptVol=0)
2024-11-19 17:53:00.233 WARNING (MainThread) [custom_components.mg_saic] Data invalid or generic: Generic charging response received.
2024-11-19 17:53:00.234 INFO (MainThread) [custom_components.mg_saic] Retrying in 15 seconds... (Attempt 1/5)
2024-11-19 17:53:18.627 DEBUG (MainThread) [custom_components.mg_saic] Generic Charging Data: ChrgMgmtData(bmsAdpPubChrgSttnDspCmd=0, bmsAltngChrgCrntDspCmd=0, bmsChrgCtrlDspCmd=0, bmsChrgOtptCrntReq=511, bmsChrgOtptCrntReqV=1, bmsChrgSpRsn=0, bmsChrgSts=0, bmsDsChrgSpRsn=0, bmsEstdElecRng=2046, bmsOnBdChrgTrgtSOCDspCmd=0, bmsPackCrnt=65535, bmsPackCrntV=1, bmsPackSOCDsp=1023, bmsPackVol=4095, bmsPTCHeatReqDspCmd=0, bmsPTCHeatResp=0, bmsPTCHeatSpRsn=None, bmsReserCtrlDspCmd=0, bmsReserSpHourDspCmd=30, bmsReserSpMintueDspCmd=62, bmsReserStHourDspCmd=30, bmsReserStMintueDspCmd=62, ccuEleccLckCtrlDspCmd=0, ccuOffBdChrgrPlugOn=0, ccuOnbdChrgrPlugOn=0, chrgngAddedElecRng=0, chrgngAddedElecRngV=0, chrgngDoorOpenCnd=0, chrgngDoorPosSts=0, chrgngRmnngTime=1023, chrgngRmnngTimeV=1, chrgngSpdngTime=0, chrgngSpdngTimeV=0, clstrElecRngToEPT=2046, disChrgngRmnngTime=1023, disChrgngRmnngTimeV=1, imcuChrgngEstdElecRng=2046, imcuChrgngEstdElecRngV=1, imcuDschrgngEstdElecRng=4095, imcuDschrgngEstdElecRngV=1, imcuVehElecRng=2046, imcuVehElecRngV=1, onBdChrgrAltrCrntInptCrnt=0, onBdChrgrAltrCrntInptVol=0)
2024-11-19 17:53:18.627 WARNING (MainThread) [custom_components.mg_saic] Data invalid or generic: Generic charging response received.
2024-11-19 17:53:18.627 INFO (MainThread) [custom_components.mg_saic] Retrying in 15 seconds... (Attempt 2/5)
2024-11-19 17:53:36.993 DEBUG (MainThread) [custom_components.mg_saic] Generic Charging Data: ChrgMgmtData(bmsAdpPubChrgSttnDspCmd=0, bmsAltngChrgCrntDspCmd=0, bmsChrgCtrlDspCmd=0, bmsChrgOtptCrntReq=511, bmsChrgOtptCrntReqV=1, bmsChrgSpRsn=0, bmsChrgSts=0, bmsDsChrgSpRsn=0, bmsEstdElecRng=2046, bmsOnBdChrgTrgtSOCDspCmd=0, bmsPackCrnt=65535, bmsPackCrntV=1, bmsPackSOCDsp=1023, bmsPackVol=4095, bmsPTCHeatReqDspCmd=0, bmsPTCHeatResp=0, bmsPTCHeatSpRsn=None, bmsReserCtrlDspCmd=0, bmsReserSpHourDspCmd=30, bmsReserSpMintueDspCmd=62, bmsReserStHourDspCmd=30, bmsReserStMintueDspCmd=62, ccuEleccLckCtrlDspCmd=0, ccuOffBdChrgrPlugOn=0, ccuOnbdChrgrPlugOn=0, chrgngAddedElecRng=0, chrgngAddedElecRngV=0, chrgngDoorOpenCnd=0, chrgngDoorPosSts=0, chrgngRmnngTime=1023, chrgngRmnngTimeV=1, chrgngSpdngTime=0, chrgngSpdngTimeV=0, clstrElecRngToEPT=2046, disChrgngRmnngTime=1023, disChrgngRmnngTimeV=1, imcuChrgngEstdElecRng=2046, imcuChrgngEstdElecRngV=1, imcuDschrgngEstdElecRng=4095, imcuDschrgngEstdElecRngV=1, imcuVehElecRng=2046, imcuVehElecRngV=1, onBdChrgrAltrCrntInptCrnt=0, onBdChrgrAltrCrntInptVol=0)
2024-11-19 17:53:36.993 WARNING (MainThread) [custom_components.mg_saic] Data invalid or generic: Generic charging response received.
2024-11-19 17:53:36.993 INFO (MainThread) [custom_components.mg_saic] Retrying in 15 seconds... (Attempt 3/5)
2024-11-19 17:53:45.650 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('mg_saic', '01JD2F31060Z1YR1K82KS7R2P5'): 132555.898310899}
2024-11-19 17:53:55.359 DEBUG (MainThread) [custom_components.mg_saic] Generic Charging Data: ChrgMgmtData(bmsAdpPubChrgSttnDspCmd=0, bmsAltngChrgCrntDspCmd=0, bmsChrgCtrlDspCmd=0, bmsChrgOtptCrntReq=511, bmsChrgOtptCrntReqV=1, bmsChrgSpRsn=0, bmsChrgSts=0, bmsDsChrgSpRsn=0, bmsEstdElecRng=2046, bmsOnBdChrgTrgtSOCDspCmd=0, bmsPackCrnt=65535, bmsPackCrntV=1, bmsPackSOCDsp=1023, bmsPackVol=4095, bmsPTCHeatReqDspCmd=0, bmsPTCHeatResp=0, bmsPTCHeatSpRsn=None, bmsReserCtrlDspCmd=0, bmsReserSpHourDspCmd=30, bmsReserSpMintueDspCmd=62, bmsReserStHourDspCmd=30, bmsReserStMintueDspCmd=62, ccuEleccLckCtrlDspCmd=0, ccuOffBdChrgrPlugOn=0, ccuOnbdChrgrPlugOn=0, chrgngAddedElecRng=0, chrgngAddedElecRngV=0, chrgngDoorOpenCnd=0, chrgngDoorPosSts=0, chrgngRmnngTime=1023, chrgngRmnngTimeV=1, chrgngSpdngTime=0, chrgngSpdngTimeV=0, clstrElecRngToEPT=2046, disChrgngRmnngTime=1023, disChrgngRmnngTimeV=1, imcuChrgngEstdElecRng=2046, imcuChrgngEstdElecRngV=1, imcuDschrgngEstdElecRng=4095, imcuDschrgngEstdElecRngV=1, imcuVehElecRng=2046, imcuVehElecRngV=1, onBdChrgrAltrCrntInptCrnt=0, onBdChrgrAltrCrntInptVol=0)
2024-11-19 17:53:55.360 WARNING (MainThread) [custom_components.mg_saic] Data invalid or generic: Generic charging response received.
2024-11-19 17:53:55.360 INFO (MainThread) [custom_components.mg_saic] Retrying in 15 seconds... (Attempt 4/5)
2024-11-19 17:54:13.832 DEBUG (MainThread) [custom_components.mg_saic] Generic Charging Data: ChrgMgmtData(bmsAdpPubChrgSttnDspCmd=0, bmsAltngChrgCrntDspCmd=0, bmsChrgCtrlDspCmd=0, bmsChrgOtptCrntReq=511, bmsChrgOtptCrntReqV=1, bmsChrgSpRsn=0, bmsChrgSts=0, bmsDsChrgSpRsn=0, bmsEstdElecRng=2046, bmsOnBdChrgTrgtSOCDspCmd=0, bmsPackCrnt=65535, bmsPackCrntV=1, bmsPackSOCDsp=1023, bmsPackVol=4095, bmsPTCHeatReqDspCmd=0, bmsPTCHeatResp=0, bmsPTCHeatSpRsn=None, bmsReserCtrlDspCmd=0, bmsReserSpHourDspCmd=30, bmsReserSpMintueDspCmd=62, bmsReserStHourDspCmd=30, bmsReserStMintueDspCmd=62, ccuEleccLckCtrlDspCmd=0, ccuOffBdChrgrPlugOn=0, ccuOnbdChrgrPlugOn=0, chrgngAddedElecRng=0, chrgngAddedElecRngV=0, chrgngDoorOpenCnd=0, chrgngDoorPosSts=0, chrgngRmnngTime=1023, chrgngRmnngTimeV=1, chrgngSpdngTime=0, chrgngSpdngTimeV=0, clstrElecRngToEPT=2046, disChrgngRmnngTime=1023, disChrgngRmnngTimeV=1, imcuChrgngEstdElecRng=2046, imcuChrgngEstdElecRngV=1, imcuDschrgngEstdElecRng=4095, imcuDschrgngEstdElecRngV=1, imcuVehElecRng=2046, imcuVehElecRngV=1, onBdChrgrAltrCrntInptCrnt=0, onBdChrgrAltrCrntInptVol=0)
2024-11-19 17:54:13.832 WARNING (MainThread) [custom_components.mg_saic] Data invalid or generic: Generic charging response received.
2024-11-19 17:54:13.833 INFO (MainThread) [custom_components.mg_saic] Retrying in 15 seconds... (Attempt 5/5)
2024-11-19 17:54:28.833 ERROR (MainThread) [custom_components.mg_saic] Failed to fetch data after 5 retries.
2024-11-19 17:54:28.834 DEBUG (MainThread) [custom_components.mg_saic] Finished fetching MG SAIC data update coordinator data in 94.912 seconds (success: True)
2024-11-19 17:54:28.859 ERROR (MainThread) [custom_components.mg_saic] Failed to retrieve vehicle info or status.
2024-11-19 17:54:28.859 ERROR (MainThread) [custom_components.mg_saic] Failed to retrieve vehicle info or status.
2024-11-19 17:54:28.859 ERROR (MainThread) [custom_components.mg_saic] Failed to retrieve vehicle info or status.
2024-11-19 17:54:28.859 ERROR (MainThread) [homeassistant.components.button] Error while setting up mg_saic platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mg_saic/button.py", line 11, in async_setup_entry
    vin_info = coordinator.data["info"][0]
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-11-19 17:54:28.863 ERROR (MainThread) [homeassistant.components.climate] Error while setting up mg_saic platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mg_saic/climate.py", line 23, in async_setup_entry
    vin_info = coordinator.data["info"][0]
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-11-19 17:54:28.864 ERROR (MainThread) [homeassistant.components.number] Error while setting up mg_saic platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mg_saic/number.py", line 11, in async_setup_entry
    vin_info = coordinator.data["info"][0]
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-11-19 17:54:28.865 ERROR (MainThread) [homeassistant.components.switch] Error while setting up mg_saic platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mg_saic/switch.py", line 10, in async_setup_entry
    vin_info = coordinator.data["info"][0]
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-11-19 17:54:28.866 ERROR (MainThread) [homeassistant.components.lock] Error while setting up mg_saic platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/mg_saic/lock.py", line 10, in async_setup_entry
    vin_info = coordinator.data["info"][0]
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-11-19 17:54:28.868 INFO (MainThread) [custom_components.mg_saic] Services registered for MG SAIC integration.
2024-11-19 17:54:28.868 INFO (MainThread) [custom_components.mg_saic] MG SAIC integration setup completed successfully.
```

**Comment by ad-ha** [comment]
Thanks @nestor1832

With those full logs I will try to find a workaround.

Seems like you keep having the same issue with the Charging Data being only generic.

I am wondering if I can break the data update into different blocks. Let me check if I find a way.

**Comment by nestor1832** [comment]
I just want to give you some information about ISmart with my vehicle. (MG EH32 X7)
If I don't do a full scan of the vehicle's status, every other time it fails to show me the vehicle's range and remaining mileage.
I don't know if this is useful information ;-)
![Screenshot_20241119_212829_MG iSMART](https://github.com/user-attachments/assets/de4cc542-db21-4152-8f49-80f142119c7b)
![Screenshot_20241119_212842_MG iSMART](https://github.com/user-attachments/assets/77eb27fa-a174-4e8e-bda8-618497aab67c)

**Comment by ad-ha** [comment]
Hi @nestor1832 

> I just want to give you some information about ISmart with my vehicle. (MG EH32 X7)
> If I don't do a full scan of the vehicle's status, every other time it fails to show me the vehicle's range and remaining mileage.
> I don't know if this is useful information ;-)

That's the issue behind generic responses, that not even MG App fully updates and sometimes you need to refresh several times. IN my case, sometimes I need to hit refresh 3 or 4 times (not always) before I get any data on that or even on the charging data.

I am trying to find a solution for the matter. I will try to get the updates broken into different stages, instead of a big one like it was now.

Let's see if I can get this done tomorrow.

**Comment by ad-ha** [comment]
HI @nestor1832 

Let's see if version 0.5.0 helps on your case and we can get this improved 😄 

Cheers

**Comment by dvptommy** [comment]
I have exactly the same and am on 0.5.2.

**Comment by ad-ha** [comment]
> I have exactly the same and am on 0.5.2. 

@dvptommy do you have the logs to check the issue, please?

**Comment by dvptommy** [comment]
Hi, is this what you need?
[image0.png][image1.png][image2.png][image3.png][image4.png][image6.png][image6.png][image7.png]

On 22 Nov 2024, at 21:05, Alvaro Duarte ***@***.***> wrote:

﻿

I have exactly the same and am on 0.5.2.

@dvptommy<https://github.com/dvptommy> do you have the logs to check the issue, please?

**Comment by ad-ha** [comment]
@dvptommy

Maybe,but you have to respond on Github, not by email, as the images do not parse through.

**Comment by dvptommy** [comment]
@ad-ha and here's the condensed version:

ailed to fetch charging info after 5 retries. 
 17:36:09 – (ERROR) MG SAIC (custom integration) - message first occurred at 16:35:21 and shows up 3 times
 Error fetching vehicle info: Vehicle info is None.. Retrying in 15 seconds... (Attempt 1/5) 
 17:35:54 – (WARNING) MG SAIC (custom integration) - message first occurred at 16:32:01 and shows up 21 times
 Charging info returned None. 
 17:35:54 – (WARNING) MG SAIC (custom integration) - message first occurred at 16:32:01 and shows up 21 times
 Error retrieving vehicle info: return code: 401, message: {"code":401,"message":"Token missing, Authentication failed!"} 
 17:35:54 – (ERROR) MG SAIC (custom integration) - message first occurred at 17:03:38 and shows up 10 times
 Error setting up entry MG SAIC - LSJWN5061RN149030 for mg_saic 
 17:31:38 – (ERROR) config_entries.py - message first occurred at 17:01:53 and shows up 4 times
 Error retrieving charging information: return code: 4, message: The remote control instruction failed, please try again later., event_id: 1671507416 
 17:31:16 – (ERROR) MG SAIC (custom integration) - message first occurred at 16:32:01 and shows up 11 times
 Error fetching MG SAIC data update coordinator data: Cannot proceed without vehicle info. 
 17:04:53 – (ERROR) MG SAIC (custom integration)
 Error opening sunroof for VIN LSJWN5061RN149030: return code: 401, message: {"code":401,"message":"Token expired"} 
 17:02:40 – (ERROR) MG SAIC (custom integration)
 Error controlling sunroof for VIN LSJWN5061RN149030: return code: 401, message: {"code":401,"message":"Token expired"} 
 17:02:40 – (ERROR) MG SAIC (custom integration)
 Not retrying since we got logged out 
 17:02:40 – (ERROR) MG SAIC (custom integration)
 Error setting up entry MG SAIC - LSJWN5061RN149030 for mg_saic 
 16:36:45 – (ERROR) config_entries.py
 Error setting up entry MG SAIC - LSJWN5061RN149030 for sensor 
 16:36:45 – (ERROR) config_entries.py
 Waiting on integrations to complete setup: {('better_thermostat', '01JD376YENYYJ2QRGY0NKD18RE'): 131.183460725, ('mg_saic', '01JCH3GD9XVZVDZJ9QMFGDGDEX'): 135.314487248, ('icloud', '01JD367ZFST9Z4H74ZQ0M654K8'): 135.50699741, ('zha', 'd74f0bc92060cbfebbfff15fc9de477e'): 141.48230288, ('hon', '01JD362MVF5H47SYV0G0Z54ERV'): 141.526226322, ('mqtt', '55cda639f655a7cc0e729f954e7719be'): 145.211318715, ('lg_thinq', '01JD33J80X1NDK697DVSCFEF2C'): 147.174385736, ('heatmiserneo', '01JAHT449KFJNGPYEKYPETPDR2'): 147.340348707, ('samsungtv', '1edd3b0d0e4263eb6baeaf36e622064d'): 148.148257247, ('emporia_vue', 'b5023013e1a7f5ee081d9e4368cf8c3b'): 148.21960504, ('hikvision_next', '18f3883e0ff6228b4ad0c84bb91cc291'): 148.676111176, ('roomba', 'f10f3631e65d63169242066c0c4f2a77'): 149.314971053, ('ruckus_unleashed', '054c11ef827a507b2a97544b15af861c'): 149.554346481, ('oralb', 'ead3d6749341f33574cd73c66bfb27d1'): 154.83517195, ('ibeacon', '57794f1c015b7c0af666a3eeb007ee9f'): 154.889063907, ('switchbot', '310c51df347a4c68dce2d1d3157cd695'): 155.736000093, ('switchbot', 'ca2c6b76166ab67797d474b0349bdc3d'): 155.738275697, ('switchbot', '01J2NDZGTRQCJE14M49B0B5C0C'): 155.74071024, ('netatmo', '93bff16af26a6681bf6a84a712d502af'): 156.706968936, ('yale', '01J724AGCHRX2T5DHVMP7WV17Q'): 160.041351142, ('homekit_controller', None): 165.13228273, ('wyoming', '27e1057975f83fe042b4529e84f4a777'): 167.549335894} 
 16:36:44 – (WARNING) bootstrap.py - message first occurred at 16:31:40 and shows up 6 times
 Setup of sensor platform mg_saic is taking over 10 seconds. 
 16:35:31 – (WARNING) Sensor

**Comment by ad-ha** [comment]
@dvptommy

I can see the issue, but you need to activate the debug logs and get those.

Those are general logs that do not show the underlying issues.

Anyhow, seems like the integration cannot get the data from the API for your vehicle.

**Comment by ad-ha** [comment]
@dvptommy here you go:

Logs
Add the following to your configuration.yaml on your Home Assistant and restart:

```
logger:
  default: warning
  logs:
    custom_components.mg_saic: debug
```
See [Home Assistant Logger Documentation](https://www.home-assistant.io/integrations/logger) for more information.

**Comment by dvptommy** [comment]
Hi @ad-ha , this is what you need?

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 577, in ensure_valid
    self._compiled_code = self._env.compile(self.template)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 3212, in compile
    compiled = super().compile(source)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 52, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '>'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 750, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 627, in async_render
    compiled = self._compiled or self._ensure_compiled(limited, strict, log_fn)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 831, in _ensure_compiled
    self.ensure_valid()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 579, in ensure_valid
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TemplateSyntaxError: unexpected '>'[0m
[33m2024-11-29 20:08:36.499 WARNING (Thread-2 (_thread_main)) [roombapy.roomba] Error looking up Roomba error message: 231[0m
[36m2024-11-29 20:08:49.877 DEBUG (MainThread) [custom_components.mg_saic] Logging in with base URL: https://gateway-mg-eu.soimt.com/api.app/v1/ for region: EU[0m
[36m2024-11-29 20:08:51.607 DEBUG (MainThread) [custom_components.mg_saic] Login successful, initializing vehicle APIs.[0m
[31m2024-11-29 20:09:44.708 ERROR (MainThread) [custom_components.mg_saic] Error retrieving charging information: return code: 4, message: The remote control instruction failed, please try again later., event_id: 270934636[0m
[33m2024-11-29 20:09:44.708 WARNING (MainThread) [custom_components.mg_saic] Charging info returned None.[0m
[33m2024-11-29 20:09:44.708 WARNING (MainThread) [custom_components.mg_saic] Error fetching charging info: Charging info is None.. Retrying in 15 seconds... (Attempt 1/5)[0m
[36m2024-11-29 20:09:49.978 DEBUG (MainThread) [custom_components.mg_saic] Finished fetching MG SAIC data update coordinator data in 58.265 seconds (success: True)[0m
[31m2024-11-29 20:09:49.978 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MG SAIC - LSJWN5061RN149030 for mg_saic
Traceback (most recent call last):
  File "/config/custom_components/mg_saic/coordinator.py", line 127, in _fetch_with_retries
    raise UpdateFailed(f"{data_name.capitalize()} is None.")
homeassistant.helpers.update_coordinator.UpdateFailed: Charging info is None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/__init__.py", line 42, in async_setup_entry
    await coordinator.async_setup()
  File "/config/custom_components/mg_saic/coordinator.py", line 54, in async_setup
    await self.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 309, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/coordinator.py", line 87, in _async_update_data
    data["charging"] = await self._fetch_with_retries(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/coordinator.py", line 143, in _fetch_with_retries
    await asyncio.sleep(delay)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError[0m

**Comment by ad-ha** [comment]
### CLOSE

This thread did not have any activity over 2-weeks, so I consider the issue has been sorted.
