### ISSUE TITLE
[ISSUE] Configuration button gives "500 Internal Server Error Server got itself in trouble"

### ISSUE THREAD

**Issue by fulesfules** [ad-ha/mg-saic-ha#73]
### Home Assistant Version

2024.11.2

### MG/SAIC Integration Version

0.8.1

### Installation Method

HACS

### Did you check for existing issues?

- [X] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [X] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

Updated from the latest 0.7 to 0.8.1, and now I got an error clicking on the "Configuration" button,. 
I even deleted and readded my vehicle, but the error is the same.

``

### Logs

```yaml
Napló: aiohttp.server
Forrás: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
Először fordult elő: 10:00:50 (5 Események)
Utoljára naplózva: 10:03:52

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 342, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mg_saic/config_flow.py", line 248, in async_step_init
    self.options = self.config_entry.options
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'SAICMGOptionsFlowHandler' object has no attribute 'config_entry'







Ez a hiba egy egyéni integrációból származik.

Napló: custom_components.mg_saic
Forrás: custom_components/mg_saic/api.py:64
integráció: MG SAIC (dokumentáció, problémák)
Először fordult elő: 10:02:50 (1 Események)
Utoljára naplózva: 10:02:50

API call failed: return code: 4, message: The remote control instruction failed, please try again later., event_id: 1580396725



Ez a hiba egy egyéni integrációból származik.

Napló: custom_components.mg_saic
Forrás: custom_components/mg_saic/api.py:130
integráció: MG SAIC (dokumentáció, problémák)
Először fordult elő: 10:02:50 (1 Események)
Utoljára naplózva: 10:02:50

Error retrieving vehicle status: return code: 4, message: The remote control instruction failed, please try again later., event_id: 1580396725


Ez a hiba egy egyéni integrációból származik.

Napló: custom_components.mg_saic
Forrás: custom_components/mg_saic/coordinator.py:673
integráció: MG SAIC (dokumentáció, problémák)
Először fordult elő: 10:02:50 (1 Események)
Utoljára naplózva: 10:02:50

Vehicle status returned None.

Ez a hiba egy egyéni integrációból származik.

Napló: custom_components.mg_saic
Forrás: custom_components/mg_saic/coordinator.py:682
integráció: MG SAIC (dokumentáció, problémák)
Először fordult elő: 10:02:50 (1 Események)
Utoljára naplózva: 10:02:50

Error fetching vehicle status: Vehicle status is None.. Retrying in 15 seconds... (Attempt 1/5)
```

**Comment by ad-ha** [comment]
Hi @fulesfules 

I think the issue is with your HA version. From 2024.12 there was a deprecation warning on the usage of config_flow entry. To solve that, the integration has been updated to solve that issue for the current 2024.12 and future versions.

I recommend you update your instance and check if the error still occurs. On my case, it is working without any issues.

Let me know once you do that.

**Comment by fulesfules** [comment]
Yes, it did the trick. Thanks.
